export interface EmailTemplateData {
  summary: string;
  meetingDate?: string;
  subject?: string;
}

export const EMAIL_TEMPLATE = {
  subject: (meetingDate?: string) => 
    meetingDate ? `Meeting Summary - ${meetingDate}` : 'Meeting Summary',
  
  body: (summary: string, meetingDate?: string) => `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Meeting Summary</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }
    .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; border-radius: 10px; text-align: center; margin-bottom: 30px; }
    .header h1 { margin: 0; font-size: 28px; font-weight: 600; }
    .header p { margin: 10px 0 0 0; opacity: 0.9; }
    .content { background: #f8f9fa; padding: 30px; border-radius: 10px; border-left: 4px solid #667eea; }
    .summary { background: white; padding: 25px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
    .footer { text-align: center; margin-top: 30px; padding: 20px; color: #666; font-size: 14px; border-top: 1px solid #eee; }
    h2, h3 { color: #2c3e50; }
    ul, ol { padding-left: 20px; }
    li { margin-bottom: 8px; }
    strong { color: #2c3e50; }
  </style>
</head>
<body>
  <div class="header">
    <h1>📋 Meeting Summary</h1>
    ${meetingDate ? `<p>Generated on ${meetingDate}</p>` : '<p>AI-Generated Summary</p>'}
  </div>
  
  <div class="content">
    <div class="summary">
      ${summary.replace(/\n/g, '<br>').replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')}
    </div>
  </div>
  
  <div class="footer">
    <p>This summary was automatically generated by AI Meeting Summarizer</p>
    <p>📧 If you have any questions about this summary, please reach out to the meeting organizer.</p>
  </div>
</body>
</html>`,

  plainText: (summary: string, meetingDate?: string) => `
MEETING SUMMARY
${meetingDate ? `Date: ${meetingDate}` : 'AI-Generated Summary'}
${'='.repeat(50)}

${summary}

${'='.repeat(50)}
This summary was automatically generated by AI Meeting Summarizer.
`
};

export const formatEmailContent = (
  summary: string, 
  format: 'html' | 'plain' = 'html',
  meetingDate?: string
) => {
  return format === 'html' 
    ? EMAIL_TEMPLATE.body(summary, meetingDate)
    : EMAIL_TEMPLATE.plainText(summary, meetingDate);
};
